kind: pipeline
name: default

steps:
  - name: test
    image: node
    commands:
      - npm install 
      - npm run test

  - name: test
    image: node
    commands:
      - npm install 
      - npm run test:e2e
