kind: pipeline
name: default

steps:
  - name: test
    image: node
    commands:
      - npm install 
      - npm run test

  - name: e2e-test
    image: node
    commands:
      - npm install 
      - npm run test:e2e
  - name: docker  
    image: plugins/docker
    settings:
      repo:  azurelynx.com:5000/test
      registry: azurelynx.com:5000